Rust kit
Lux-AI-Challenge/Lux-Design-S2 pull request #226
Opened 2023-03-01 15:17 UTC by Seamooo

closes #111 

Remaining work:
- [ ] Better path finding
- [ ] Forward sim?
- [ ] Errors over panics
- [ ] Executable verification
- [ ] Coverage tests
- [ ] Integration tests

Clarifications:
- Are factories guaranteed to to have an origin at least `(1,1)`, and at most `(size-2, size-2)`?
- Are the player ids guaranteed to be `player_0`, `player_1` every match? If so
  is it worthwhile calling them a generic player_id or just denoting them the
  same way `LIGHT` and `HEAVY` is denoted?
- What's the use of factions / should names outside of the 4 valid values be supported?
- I've seen some implementations use BigInteger representations for bid amounts, is this necessary?

2023-03-06 08:23 UTC, Seamooo commented
- Better path finding has been labelled as a nice to have once confirming that submitting an invalid action in the demo doesn't cause a crash
- Forward sim has not been implemented as it seems like effectively a no-op in the python implementation due to simulating actions not being possible
- Executable has been verified for Linux and Windows platforms
- Coverage tests have been written for code outside of serializing / deserializing and communication
- Integration tests take the form of the demo

2023-03-08 04:43 UTC, Seamooo commented
@StoneT2000 is there anything additional required to get this merged?

2023-03-08 22:23 UTC, StoneT2000 commented
Thanks for the contribution @Seamooo I will try to review it this weekend and give feedback on what might need changing.

2023-03-14 03:51 UTC, StoneT2000 requested changes

2023-03-14 03:51 UTC, StoneT2000 commented on kits/rust/README.md
> +- What's the use of factions / should names outside of the 4 valid values be supported
Factions are currently unused, but there is only those 4 values. Feel free to remove this section.

2023-03-23 03:59 UTC, StoneT2000 approved these changes

2023-03-23 03:59 UTC, merged

2023-03-23 03:59 UTC, StoneT2000 commented
thank you for the contribution! @Seamooo